rootProject.name = "florify"

include("common")
include("auth-service")
include("inventory-service")
include("order-service")
include("customer-service")
include("product-catalog-service")
include("supplier-service")
include("employee-service")
include("media-service")
include("notification-service")
include("delivery-service")
include("finance-service")
include("analytics-service")
include("store-service")
include("florify-app")
